// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Generates src/lokum/styles/lokum-content-flavors.css from the flavor
// palettes in LokumFlavors.sys.mjs. Pages in content processes (new tab,
// private browsing) cannot run Lokum's chrome code, so they pick the active
// flavor with `-moz-pref("lokum.flavor", "<id>")` media queries instead.
//
// usage: node scripts/dev/make_content_css.mjs [--check]

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const OUT = path.join(root, "src/lokum/styles/lokum-content-flavors.css");

export function loadFlavors() {
  const source = fs.readFileSync(path.join(root, "src/lokum/modules/LokumFlavors.sys.mjs"), "utf8");
  const block = source.slice(source.indexOf("const FLAVOR_DATA = {"), source.indexOf("export const FLAVOR_IDS"));
  return new Function(block.replace("const FLAVOR_DATA =", "return"))();
}

const pair = ([light, dark]) => `light-dark(${light}, ${dark})`;

function declarations(f) {
  return [
    ["--lk-frame-1", pair(f.frame[0])],
    ["--lk-frame-2", pair(f.frame[1])],
    ["--lk-frame-3", pair(f.frame[2])],
    ["--lk-accent", pair(f.accent)],
    ["--lk-accent-text", pair(f.accentText)],
    ["--lk-text", pair(f.text)],
    ["--lk-text-muted", pair(f.muted)],
  ]
    .map(([name, value]) => `      ${name}: ${value};`)
    .join("\n");
}

export function generate(flavors = loadFlavors()) {
  const ids = Object.keys(flavors);
  const lines = [
    "/* This Source Code Form is subject to the terms of the Mozilla Public",
    " * License, v. 2.0. If a copy of the MPL was not distributed with this",
    " * file, You can obtain one at http://mozilla.org/MPL/2.0/. */",
    "",
    "/* GENERATED by scripts/dev/make_content_css.mjs from LokumFlavors.sys.mjs.",
    " * Do not edit by hand. */",
    "",
    '@-moz-document url("about:newtab"), url("about:home"), url("about:privatebrowsing"), url("about:welcome") {',
    "  /* Default flavor (also used when the pref holds an unknown value). */",
    "  :root {",
    declarations(flavors[ids[0]]).replace(/^ {2}/gm, ""),
    "  }",
  ];
  for (const id of ids.slice(1)) {
    lines.push(
      "",
      `  @media -moz-pref("lokum.flavor", "${id}") {`,
      "    :root {",
      declarations(flavors[id]),
      "    }",
      "  }"
    );
  }
  lines.push("}", "");
  return lines.join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const css = generate();
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (current !== css) {
      console.error("lokum-content-flavors.css is out of date; run node scripts/dev/make_content_css.mjs");
      process.exit(1);
    }
    console.log("lokum-content-flavors.css is up to date");
  } else {
    fs.writeFileSync(OUT, css);
    console.log(`wrote ${path.relative(root, OUT)}`);
  }
}
