; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at http://mozilla.org/MPL/2.0/.
;
; Installer strings. One block per language, same keys in every block.

; ------------------------------------------------------------------ English
LangString WelcomeTitle ${LANG_ENGLISH} "Welcome to Lokum"
LangString WelcomeText ${LANG_ENGLISH} "Lokum is a Turkish-delight flavored web browser built on Firefox, with Arc-style spaces, a sidebar full of tabs and a dozen delicious themes.$\r$\n$\r$\nLokum installs just for you — no administrator rights needed — and keeps itself up to date automatically.$\r$\n$\r$\nClick Next to continue."
LangString OptionsTitle ${LANG_ENGLISH} "A few choices"
LangString OptionsSubtitle ${LANG_ENGLISH} "You can change all of this later in Lokum Settings."
LangString OptionsIntro ${LANG_ENGLISH} "Pick your flavor, layout and spaces on the first launch. For now:"
LangString OptDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString OptDefault ${LANG_ENGLISH} "Make Lokum my default browser"
LangString OptUblock ${LANG_ENGLISH} "Install uBlock Origin ad blocker (recommended)"
LangString OptionsNote ${LANG_ENGLISH} "Lokum sends no telemetry. Updates are downloaded from GitHub and verified before they are installed."
LangString FinishTitle ${LANG_ENGLISH} "Lokum is ready!"
LangString FinishText ${LANG_ENGLISH} "Lokum has been installed on your computer. Enjoy your sweet browsing!"
LangString LaunchNow ${LANG_ENGLISH} "Open Lokum now"
LangString ProjectLink ${LANG_ENGLISH} "Lokum on GitHub"
LangString NeedsWin10 ${LANG_ENGLISH} "Lokum requires Windows 10 or later."
LangString Needs64Bit ${LANG_ENGLISH} "This version of Lokum requires 64-bit Windows."
LangString CloseLokum ${LANG_ENGLISH} "Lokum is still running. Please close all Lokum windows and click Retry."
LangString Preparing ${LANG_ENGLISH} "Preparing…"
LangString Copying ${LANG_ENGLISH} "Unwrapping your Lokum…"
LangString AppDescription ${LANG_ENGLISH} "Lokum — a sweeter way to browse"
LangString UnDataTitle ${LANG_ENGLISH} "Your browsing data"
LangString UnDataSubtitle ${LANG_ENGLISH} "Bookmarks, history, passwords and settings"
LangString UnDataText ${LANG_ENGLISH} "Lokum keeps your bookmarks, history, passwords and settings in your user profile. Keep them if you might reinstall Lokum later."
LangString UnDataCheckbox ${LANG_ENGLISH} "Also delete my Lokum browsing data"

; ------------------------------------------------------------------ Turkish
LangString WelcomeTitle ${LANG_TURKISH} "Lokum'a hoş geldin"
LangString WelcomeText ${LANG_TURKISH} "Lokum; Firefox tabanlı, Arc tarzı alanları, sekmelerle dolu kenar çubuğu ve bir düzine lezzetli temasıyla lokum tadında bir web tarayıcısıdır.$\r$\n$\r$\nLokum yalnızca senin kullanıcı hesabına kurulur — yönetici izni gerekmez — ve kendini otomatik olarak güncel tutar.$\r$\n$\r$\nDevam etmek için İleri'ye tıkla."
LangString OptionsTitle ${LANG_TURKISH} "Birkaç seçim"
LangString OptionsSubtitle ${LANG_TURKISH} "Bunların hepsini daha sonra Lokum Ayarları'ndan değiştirebilirsin."
LangString OptionsIntro ${LANG_TURKISH} "Lezzetini, düzenini ve alanlarını ilk açılışta seçeceksin. Şimdilik:"
LangString OptDesktop ${LANG_TURKISH} "Masaüstüne kısayol oluştur"
LangString OptDefault ${LANG_TURKISH} "Lokum'u varsayılan tarayıcım yap"
LangString OptUblock ${LANG_TURKISH} "uBlock Origin reklam engelleyiciyi kur (önerilir)"
LangString OptionsNote ${LANG_TURKISH} "Lokum hiçbir telemetri verisi göndermez. Güncellemeler GitHub'dan indirilir ve kurulmadan önce doğrulanır."
LangString FinishTitle ${LANG_TURKISH} "Lokum hazır!"
LangString FinishText ${LANG_TURKISH} "Lokum bilgisayarına kuruldu. Tatlı gezintiler!"
LangString LaunchNow ${LANG_TURKISH} "Lokum'u şimdi aç"
LangString ProjectLink ${LANG_TURKISH} "GitHub'da Lokum"
LangString NeedsWin10 ${LANG_TURKISH} "Lokum, Windows 10 veya daha yeni bir sürüm gerektirir."
LangString Needs64Bit ${LANG_TURKISH} "Lokum'un bu sürümü 64 bit Windows gerektirir."
LangString CloseLokum ${LANG_TURKISH} "Lokum hâlâ çalışıyor. Lütfen tüm Lokum pencerelerini kapatıp Yeniden Dene'ye tıkla."
LangString Preparing ${LANG_TURKISH} "Hazırlanıyor…"
LangString Copying ${LANG_TURKISH} "Lokum'un paketi açılıyor…"
LangString AppDescription ${LANG_TURKISH} "Lokum — gezinmenin tatlı hâli"
LangString UnDataTitle ${LANG_TURKISH} "Tarama verilerin"
LangString UnDataSubtitle ${LANG_TURKISH} "Yer imleri, geçmiş, parolalar ve ayarlar"
LangString UnDataText ${LANG_TURKISH} "Lokum yer imlerini, geçmişini, parolalarını ve ayarlarını kullanıcı profilinde saklar. Lokum'u daha sonra yeniden kurabilirsen bunları sakla."
LangString UnDataCheckbox ${LANG_TURKISH} "Lokum tarama verilerimi de sil"

; ------------------------------------------------------------------- German
LangString WelcomeTitle ${LANG_GERMAN} "Willkommen bei Lokum"
LangString WelcomeText ${LANG_GERMAN} "Lokum ist ein Webbrowser mit Lokum-Geschmack auf Firefox-Basis – mit Bereichen im Arc-Stil, einer Seitenleiste voller Tabs und einem Dutzend köstlicher Designs.$\r$\n$\r$\nLokum wird nur für dich installiert – ohne Administratorrechte – und hält sich automatisch aktuell.$\r$\n$\r$\nKlicke auf Weiter, um fortzufahren."
LangString OptionsTitle ${LANG_GERMAN} "Ein paar Entscheidungen"
LangString OptionsSubtitle ${LANG_GERMAN} "Du kannst alles später in den Lokum-Einstellungen ändern."
LangString OptionsIntro ${LANG_GERMAN} "Geschmack, Layout und Bereiche wählst du beim ersten Start. Für jetzt:"
LangString OptDesktop ${LANG_GERMAN} "Verknüpfung auf dem Desktop erstellen"
LangString OptDefault ${LANG_GERMAN} "Lokum als Standardbrowser festlegen"
LangString OptUblock ${LANG_GERMAN} "Werbeblocker uBlock Origin installieren (empfohlen)"
LangString OptionsNote ${LANG_GERMAN} "Lokum sendet keine Telemetrie. Updates werden von GitHub geladen und vor der Installation geprüft."
LangString FinishTitle ${LANG_GERMAN} "Lokum ist bereit!"
LangString FinishText ${LANG_GERMAN} "Lokum wurde auf deinem Computer installiert. Viel Spaß beim süßen Surfen!"
LangString LaunchNow ${LANG_GERMAN} "Lokum jetzt öffnen"
LangString ProjectLink ${LANG_GERMAN} "Lokum auf GitHub"
LangString NeedsWin10 ${LANG_GERMAN} "Lokum benötigt Windows 10 oder neuer."
LangString Needs64Bit ${LANG_GERMAN} "Diese Version von Lokum benötigt 64-Bit-Windows."
LangString CloseLokum ${LANG_GERMAN} "Lokum läuft noch. Bitte schließe alle Lokum-Fenster und klicke auf Wiederholen."
LangString Preparing ${LANG_GERMAN} "Wird vorbereitet …"
LangString Copying ${LANG_GERMAN} "Dein Lokum wird ausgepackt …"
LangString AppDescription ${LANG_GERMAN} "Lokum – süßer surfen"
LangString UnDataTitle ${LANG_GERMAN} "Deine Browserdaten"
LangString UnDataSubtitle ${LANG_GERMAN} "Lesezeichen, Chronik, Passwörter und Einstellungen"
LangString UnDataText ${LANG_GERMAN} "Lokum speichert Lesezeichen, Chronik, Passwörter und Einstellungen in deinem Benutzerprofil. Behalte sie, falls du Lokum später wieder installierst."
LangString UnDataCheckbox ${LANG_GERMAN} "Auch meine Lokum-Browserdaten löschen"

; ------------------------------------------------------------------- French
LangString WelcomeTitle ${LANG_FRENCH} "Bienvenue dans Lokum"
LangString WelcomeText ${LANG_FRENCH} "Lokum est un navigateur web au parfum de loukoum, basé sur Firefox, avec des espaces façon Arc, une barre latérale pleine d'onglets et une douzaine de thèmes délicieux.$\r$\n$\r$\nLokum s'installe uniquement pour vous — sans droits d'administrateur — et se met à jour automatiquement.$\r$\n$\r$\nCliquez sur Suivant pour continuer."
LangString OptionsTitle ${LANG_FRENCH} "Quelques choix"
LangString OptionsSubtitle ${LANG_FRENCH} "Vous pourrez tout modifier plus tard dans les paramètres de Lokum."
LangString OptionsIntro ${LANG_FRENCH} "Vous choisirez saveur, disposition et espaces au premier lancement. Pour l'instant :"
LangString OptDesktop ${LANG_FRENCH} "Créer un raccourci sur le bureau"
LangString OptDefault ${LANG_FRENCH} "Faire de Lokum mon navigateur par défaut"
LangString OptUblock ${LANG_FRENCH} "Installer le bloqueur de publicités uBlock Origin (recommandé)"
LangString OptionsNote ${LANG_FRENCH} "Lokum n'envoie aucune télémétrie. Les mises à jour sont téléchargées depuis GitHub et vérifiées avant installation."
LangString FinishTitle ${LANG_FRENCH} "Lokum est prêt !"
LangString FinishText ${LANG_FRENCH} "Lokum a été installé sur votre ordinateur. Bonne navigation tout en douceur !"
LangString LaunchNow ${LANG_FRENCH} "Ouvrir Lokum maintenant"
LangString ProjectLink ${LANG_FRENCH} "Lokum sur GitHub"
LangString NeedsWin10 ${LANG_FRENCH} "Lokum nécessite Windows 10 ou une version ultérieure."
LangString Needs64Bit ${LANG_FRENCH} "Cette version de Lokum nécessite Windows 64 bits."
LangString CloseLokum ${LANG_FRENCH} "Lokum est toujours ouvert. Fermez toutes les fenêtres de Lokum puis cliquez sur Réessayer."
LangString Preparing ${LANG_FRENCH} "Préparation…"
LangString Copying ${LANG_FRENCH} "Déballage de votre Lokum…"
LangString AppDescription ${LANG_FRENCH} "Lokum — une navigation plus douce"
LangString UnDataTitle ${LANG_FRENCH} "Vos données de navigation"
LangString UnDataSubtitle ${LANG_FRENCH} "Marque-pages, historique, mots de passe et paramètres"
LangString UnDataText ${LANG_FRENCH} "Lokum conserve vos marque-pages, historique, mots de passe et paramètres dans votre profil. Gardez-les si vous pensez réinstaller Lokum."
LangString UnDataCheckbox ${LANG_FRENCH} "Supprimer aussi mes données de navigation Lokum"

; ------------------------------------------------------------------ Italian
LangString WelcomeTitle ${LANG_ITALIAN} "Benvenuto in Lokum"
LangString WelcomeText ${LANG_ITALIAN} "Lokum è un browser web al gusto di lokum basato su Firefox, con spazi in stile Arc, una barra laterale piena di schede e una dozzina di temi deliziosi.$\r$\n$\r$\nLokum si installa solo per te — senza diritti di amministratore — e si aggiorna automaticamente.$\r$\n$\r$\nFai clic su Avanti per continuare."
LangString OptionsTitle ${LANG_ITALIAN} "Qualche scelta"
LangString OptionsSubtitle ${LANG_ITALIAN} "Potrai cambiare tutto più tardi nelle impostazioni di Lokum."
LangString OptionsIntro ${LANG_ITALIAN} "Sceglierai gusto, layout e spazi al primo avvio. Per ora:"
LangString OptDesktop ${LANG_ITALIAN} "Crea un collegamento sul desktop"
LangString OptDefault ${LANG_ITALIAN} "Imposta Lokum come browser predefinito"
LangString OptUblock ${LANG_ITALIAN} "Installa il blocco pubblicità uBlock Origin (consigliato)"
LangString OptionsNote ${LANG_ITALIAN} "Lokum non invia alcuna telemetria. Gli aggiornamenti vengono scaricati da GitHub e verificati prima dell'installazione."
LangString FinishTitle ${LANG_ITALIAN} "Lokum è pronto!"
LangString FinishText ${LANG_ITALIAN} "Lokum è stato installato sul tuo computer. Buona navigazione dolcissima!"
LangString LaunchNow ${LANG_ITALIAN} "Apri Lokum ora"
LangString ProjectLink ${LANG_ITALIAN} "Lokum su GitHub"
LangString NeedsWin10 ${LANG_ITALIAN} "Lokum richiede Windows 10 o successivo."
LangString Needs64Bit ${LANG_ITALIAN} "Questa versione di Lokum richiede Windows a 64 bit."
LangString CloseLokum ${LANG_ITALIAN} "Lokum è ancora in esecuzione. Chiudi tutte le finestre di Lokum e fai clic su Riprova."
LangString Preparing ${LANG_ITALIAN} "Preparazione…"
LangString Copying ${LANG_ITALIAN} "Scartando il tuo Lokum…"
LangString AppDescription ${LANG_ITALIAN} "Lokum — un modo più dolce di navigare"
LangString UnDataTitle ${LANG_ITALIAN} "I tuoi dati di navigazione"
LangString UnDataSubtitle ${LANG_ITALIAN} "Segnalibri, cronologia, password e impostazioni"
LangString UnDataText ${LANG_ITALIAN} "Lokum conserva segnalibri, cronologia, password e impostazioni nel tuo profilo utente. Conservali se pensi di reinstallare Lokum."
LangString UnDataCheckbox ${LANG_ITALIAN} "Elimina anche i miei dati di navigazione di Lokum"

; ------------------------------------------------------------------ Spanish
LangString WelcomeTitle ${LANG_SPANISH} "Te damos la bienvenida a Lokum"
LangString WelcomeText ${LANG_SPANISH} "Lokum es un navegador web con sabor a delicia turca basado en Firefox, con espacios al estilo Arc, una barra lateral llena de pestañas y una docena de temas deliciosos.$\r$\n$\r$\nLokum se instala solo para ti — sin permisos de administrador — y se actualiza automáticamente.$\r$\n$\r$\nHaz clic en Siguiente para continuar."
LangString OptionsTitle ${LANG_SPANISH} "Unas cuantas opciones"
LangString OptionsSubtitle ${LANG_SPANISH} "Puedes cambiar todo esto más tarde en los ajustes de Lokum."
LangString OptionsIntro ${LANG_SPANISH} "Elegirás sabor, diseño y espacios en el primer inicio. Por ahora:"
LangString OptDesktop ${LANG_SPANISH} "Crear un acceso directo en el escritorio"
LangString OptDefault ${LANG_SPANISH} "Hacer de Lokum mi navegador predeterminado"
LangString OptUblock ${LANG_SPANISH} "Instalar el bloqueador de anuncios uBlock Origin (recomendado)"
LangString OptionsNote ${LANG_SPANISH} "Lokum no envía telemetría. Las actualizaciones se descargan de GitHub y se verifican antes de instalarse."
LangString FinishTitle ${LANG_SPANISH} "¡Lokum está listo!"
LangString FinishText ${LANG_SPANISH} "Lokum se ha instalado en tu equipo. ¡Disfruta de una navegación dulce!"
LangString LaunchNow ${LANG_SPANISH} "Abrir Lokum ahora"
LangString ProjectLink ${LANG_SPANISH} "Lokum en GitHub"
LangString NeedsWin10 ${LANG_SPANISH} "Lokum requiere Windows 10 o posterior."
LangString Needs64Bit ${LANG_SPANISH} "Esta versión de Lokum requiere Windows de 64 bits."
LangString CloseLokum ${LANG_SPANISH} "Lokum todavía se está ejecutando. Cierra todas las ventanas de Lokum y haz clic en Reintentar."
LangString Preparing ${LANG_SPANISH} "Preparando…"
LangString Copying ${LANG_SPANISH} "Desenvolviendo tu Lokum…"
LangString AppDescription ${LANG_SPANISH} "Lokum — una forma más dulce de navegar"
LangString UnDataTitle ${LANG_SPANISH} "Tus datos de navegación"
LangString UnDataSubtitle ${LANG_SPANISH} "Marcadores, historial, contraseñas y ajustes"
LangString UnDataText ${LANG_SPANISH} "Lokum guarda tus marcadores, historial, contraseñas y ajustes en tu perfil de usuario. Consérvalos si quizá vuelvas a instalar Lokum."
LangString UnDataCheckbox ${LANG_SPANISH} "Eliminar también mis datos de navegación de Lokum"

; ------------------------------------------------------------------ Swedish
LangString WelcomeTitle ${LANG_SWEDISH} "Välkommen till Lokum"
LangString WelcomeText ${LANG_SWEDISH} "Lokum är en webbläsare med smak av turkisk fröjd, byggd på Firefox, med utrymmen i Arc-stil, ett sidofält fullt av flikar och ett dussin läckra teman.$\r$\n$\r$\nLokum installeras bara för dig — inga administratörsrättigheter behövs — och håller sig uppdaterad automatiskt.$\r$\n$\r$\nKlicka på Nästa för att fortsätta."
LangString OptionsTitle ${LANG_SWEDISH} "Några val"
LangString OptionsSubtitle ${LANG_SWEDISH} "Du kan ändra allt detta senare i Lokums inställningar."
LangString OptionsIntro ${LANG_SWEDISH} "Smak, layout och utrymmen väljer du vid första starten. För tillfället:"
LangString OptDesktop ${LANG_SWEDISH} "Skapa en genväg på skrivbordet"
LangString OptDefault ${LANG_SWEDISH} "Gör Lokum till min standardwebbläsare"
LangString OptUblock ${LANG_SWEDISH} "Installera annonsblockeraren uBlock Origin (rekommenderas)"
LangString OptionsNote ${LANG_SWEDISH} "Lokum skickar ingen telemetri. Uppdateringar hämtas från GitHub och verifieras innan de installeras."
LangString FinishTitle ${LANG_SWEDISH} "Lokum är redo!"
LangString FinishText ${LANG_SWEDISH} "Lokum har installerats på din dator. Njut av ljuvligt surfande!"
LangString LaunchNow ${LANG_SWEDISH} "Öppna Lokum nu"
LangString ProjectLink ${LANG_SWEDISH} "Lokum på GitHub"
LangString NeedsWin10 ${LANG_SWEDISH} "Lokum kräver Windows 10 eller senare."
LangString Needs64Bit ${LANG_SWEDISH} "Den här versionen av Lokum kräver 64-bitars Windows."
LangString CloseLokum ${LANG_SWEDISH} "Lokum körs fortfarande. Stäng alla Lokum-fönster och klicka på Försök igen."
LangString Preparing ${LANG_SWEDISH} "Förbereder…"
LangString Copying ${LANG_SWEDISH} "Packar upp ditt Lokum…"
LangString AppDescription ${LANG_SWEDISH} "Lokum — ett sötare sätt att surfa"
LangString UnDataTitle ${LANG_SWEDISH} "Dina webbdata"
LangString UnDataSubtitle ${LANG_SWEDISH} "Bokmärken, historik, lösenord och inställningar"
LangString UnDataText ${LANG_SWEDISH} "Lokum sparar dina bokmärken, historik, lösenord och inställningar i din användarprofil. Behåll dem om du kanske installerar Lokum igen."
LangString UnDataCheckbox ${LANG_SWEDISH} "Ta även bort mina webbdata i Lokum"

; ------------------------------------------------------------------- Korean
LangString WelcomeTitle ${LANG_KOREAN} "Lokum에 오신 것을 환영합니다"
LangString WelcomeText ${LANG_KOREAN} "Lokum은 Firefox 기반의 터키시 딜라이트 맛 웹 브라우저로, Arc 스타일 스페이스, 탭으로 가득한 사이드바, 달콤한 테마 12가지를 제공합니다.$\r$\n$\r$\nLokum은 현재 사용자에게만 설치되어 관리자 권한이 필요 없으며, 자동으로 최신 상태를 유지합니다.$\r$\n$\r$\n계속하려면 다음을 클릭하세요."
LangString OptionsTitle ${LANG_KOREAN} "몇 가지 선택"
LangString OptionsSubtitle ${LANG_KOREAN} "모든 항목은 나중에 Lokum 설정에서 바꿀 수 있습니다."
LangString OptionsIntro ${LANG_KOREAN} "맛, 레이아웃, 스페이스는 처음 실행할 때 고릅니다. 지금은:"
LangString OptDesktop ${LANG_KOREAN} "바탕 화면에 바로 가기 만들기"
LangString OptDefault ${LANG_KOREAN} "Lokum을 기본 브라우저로 설정"
LangString OptUblock ${LANG_KOREAN} "uBlock Origin 광고 차단기 설치 (권장)"
LangString OptionsNote ${LANG_KOREAN} "Lokum은 원격 분석 데이터를 보내지 않습니다. 업데이트는 GitHub에서 내려받아 설치 전에 검증합니다."
LangString FinishTitle ${LANG_KOREAN} "Lokum 준비 완료!"
LangString FinishText ${LANG_KOREAN} "Lokum이 컴퓨터에 설치되었습니다. 달콤한 브라우징을 즐기세요!"
LangString LaunchNow ${LANG_KOREAN} "지금 Lokum 열기"
LangString ProjectLink ${LANG_KOREAN} "GitHub의 Lokum"
LangString NeedsWin10 ${LANG_KOREAN} "Lokum을 사용하려면 Windows 10 이상이 필요합니다."
LangString Needs64Bit ${LANG_KOREAN} "이 버전의 Lokum은 64비트 Windows가 필요합니다."
LangString CloseLokum ${LANG_KOREAN} "Lokum이 아직 실행 중입니다. 모든 Lokum 창을 닫은 후 다시 시도를 클릭하세요."
LangString Preparing ${LANG_KOREAN} "준비 중…"
LangString Copying ${LANG_KOREAN} "Lokum 포장을 푸는 중…"
LangString AppDescription ${LANG_KOREAN} "Lokum — 더 달콤한 브라우징"
LangString UnDataTitle ${LANG_KOREAN} "브라우징 데이터"
LangString UnDataSubtitle ${LANG_KOREAN} "북마크, 기록, 비밀번호 및 설정"
LangString UnDataText ${LANG_KOREAN} "Lokum은 북마크, 기록, 비밀번호, 설정을 사용자 프로필에 저장합니다. 나중에 Lokum을 다시 설치할 수도 있다면 보관하세요."
LangString UnDataCheckbox ${LANG_KOREAN} "Lokum 브라우징 데이터도 삭제"

; ----------------------------------------------------------------- Japanese
LangString WelcomeTitle ${LANG_JAPANESE} "Lokum へようこそ"
LangString WelcomeText ${LANG_JAPANESE} "Lokum は Firefox をベースにした、ロクム（トルコの伝統菓子）風味のウェブブラウザーです。Arc 風のスペース、タブが並ぶサイドバー、12 種類のおいしいテーマを備えています。$\r$\n$\r$\nLokum はあなたのユーザーにだけインストールされ（管理者権限は不要）、自動的に最新の状態に保たれます。$\r$\n$\r$\n続行するには [次へ] をクリックしてください。"
LangString OptionsTitle ${LANG_JAPANESE} "いくつかの選択"
LangString OptionsSubtitle ${LANG_JAPANESE} "これらはすべて後から Lokum の設定で変更できます。"
LangString OptionsIntro ${LANG_JAPANESE} "フレーバー、レイアウト、スペースは初回起動時に選べます。今は:"
LangString OptDesktop ${LANG_JAPANESE} "デスクトップにショートカットを作成する"
LangString OptDefault ${LANG_JAPANESE} "Lokum を既定のブラウザーにする"
LangString OptUblock ${LANG_JAPANESE} "広告ブロッカー uBlock Origin をインストール（推奨）"
LangString OptionsNote ${LANG_JAPANESE} "Lokum はテレメトリーを一切送信しません。更新は GitHub からダウンロードされ、インストール前に検証されます。"
LangString FinishTitle ${LANG_JAPANESE} "Lokum の準備ができました！"
LangString FinishText ${LANG_JAPANESE} "Lokum がコンピューターにインストールされました。甘いブラウジングをお楽しみください！"
LangString LaunchNow ${LANG_JAPANESE} "今すぐ Lokum を開く"
LangString ProjectLink ${LANG_JAPANESE} "GitHub の Lokum"
LangString NeedsWin10 ${LANG_JAPANESE} "Lokum には Windows 10 以降が必要です。"
LangString Needs64Bit ${LANG_JAPANESE} "このバージョンの Lokum には 64 ビット版 Windows が必要です。"
LangString CloseLokum ${LANG_JAPANESE} "Lokum がまだ実行中です。すべての Lokum ウィンドウを閉じてから [再試行] をクリックしてください。"
LangString Preparing ${LANG_JAPANESE} "準備しています…"
LangString Copying ${LANG_JAPANESE} "Lokum を開封しています…"
LangString AppDescription ${LANG_JAPANESE} "Lokum — もっと甘いブラウジング"
LangString UnDataTitle ${LANG_JAPANESE} "ブラウジングデータ"
LangString UnDataSubtitle ${LANG_JAPANESE} "ブックマーク、履歴、パスワード、設定"
LangString UnDataText ${LANG_JAPANESE} "Lokum はブックマーク、履歴、パスワード、設定をユーザープロファイルに保存しています。後で再インストールする可能性があれば残しておいてください。"
LangString UnDataCheckbox ${LANG_JAPANESE} "Lokum のブラウジングデータも削除する"

; ------------------------------------------------------ Simplified Chinese
LangString WelcomeTitle ${LANG_SIMPCHINESE} "欢迎使用 Lokum"
LangString WelcomeText ${LANG_SIMPCHINESE} "Lokum 是一款基于 Firefox、带有土耳其软糖风味的网页浏览器，拥有 Arc 风格的空间、满是标签页的侧边栏和十二款美味主题。$\r$\n$\r$\nLokum 仅为你当前的用户安装，无需管理员权限，并会自动保持最新。$\r$\n$\r$\n点击“下一步”继续。"
LangString OptionsTitle ${LANG_SIMPCHINESE} "几个选择"
LangString OptionsSubtitle ${LANG_SIMPCHINESE} "这些都可以稍后在 Lokum 设置中更改。"
LangString OptionsIntro ${LANG_SIMPCHINESE} "首次启动时你将选择口味、布局和空间。现在："
LangString OptDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString OptDefault ${LANG_SIMPCHINESE} "将 Lokum 设为默认浏览器"
LangString OptUblock ${LANG_SIMPCHINESE} "安装 uBlock Origin 广告拦截器（推荐）"
LangString OptionsNote ${LANG_SIMPCHINESE} "Lokum 不发送任何遥测数据。更新从 GitHub 下载，并在安装前经过校验。"
LangString FinishTitle ${LANG_SIMPCHINESE} "Lokum 已准备就绪！"
LangString FinishText ${LANG_SIMPCHINESE} "Lokum 已安装到你的电脑上。祝你浏览甜蜜愉快！"
LangString LaunchNow ${LANG_SIMPCHINESE} "立即打开 Lokum"
LangString ProjectLink ${LANG_SIMPCHINESE} "GitHub 上的 Lokum"
LangString NeedsWin10 ${LANG_SIMPCHINESE} "Lokum 需要 Windows 10 或更高版本。"
LangString Needs64Bit ${LANG_SIMPCHINESE} "此版本的 Lokum 需要 64 位 Windows。"
LangString CloseLokum ${LANG_SIMPCHINESE} "Lokum 仍在运行。请关闭所有 Lokum 窗口，然后点击“重试”。"
LangString Preparing ${LANG_SIMPCHINESE} "正在准备…"
LangString Copying ${LANG_SIMPCHINESE} "正在拆开你的 Lokum…"
LangString AppDescription ${LANG_SIMPCHINESE} "Lokum — 更甜蜜的浏览方式"
LangString UnDataTitle ${LANG_SIMPCHINESE} "你的浏览数据"
LangString UnDataSubtitle ${LANG_SIMPCHINESE} "书签、历史记录、密码和设置"
LangString UnDataText ${LANG_SIMPCHINESE} "Lokum 将你的书签、历史记录、密码和设置保存在用户配置文件中。如果以后可能重新安装 Lokum，请保留它们。"
LangString UnDataCheckbox ${LANG_SIMPCHINESE} "同时删除我的 Lokum 浏览数据"

; ----------------------------------------------------- Traditional Chinese
LangString WelcomeTitle ${LANG_TRADCHINESE} "歡迎使用 Lokum"
LangString WelcomeText ${LANG_TRADCHINESE} "Lokum 是一款以 Firefox 為基礎、帶有土耳其軟糖風味的網頁瀏覽器，擁有 Arc 風格的空間、滿是分頁的側邊欄與十二款美味佈景主題。$\r$\n$\r$\nLokum 只會安裝給目前的使用者，不需要系統管理員權限，並會自動保持最新。$\r$\n$\r$\n請點擊「下一步」繼續。"
LangString OptionsTitle ${LANG_TRADCHINESE} "幾個選擇"
LangString OptionsSubtitle ${LANG_TRADCHINESE} "這些之後都能在 Lokum 設定中變更。"
LangString OptionsIntro ${LANG_TRADCHINESE} "首次啟動時你將選擇口味、版面與空間。現在："
LangString OptDesktop ${LANG_TRADCHINESE} "建立桌面捷徑"
LangString OptDefault ${LANG_TRADCHINESE} "將 Lokum 設為預設瀏覽器"
LangString OptUblock ${LANG_TRADCHINESE} "安裝 uBlock Origin 廣告封鎖器（推薦）"
LangString OptionsNote ${LANG_TRADCHINESE} "Lokum 不會傳送任何遙測資料。更新會從 GitHub 下載，並在安裝前經過驗證。"
LangString FinishTitle ${LANG_TRADCHINESE} "Lokum 已準備就緒！"
LangString FinishText ${LANG_TRADCHINESE} "Lokum 已安裝到你的電腦。祝你瀏覽甜蜜愉快！"
LangString LaunchNow ${LANG_TRADCHINESE} "立即開啟 Lokum"
LangString ProjectLink ${LANG_TRADCHINESE} "GitHub 上的 Lokum"
LangString NeedsWin10 ${LANG_TRADCHINESE} "Lokum 需要 Windows 10 或更新版本。"
LangString Needs64Bit ${LANG_TRADCHINESE} "此版本的 Lokum 需要 64 位元 Windows。"
LangString CloseLokum ${LANG_TRADCHINESE} "Lokum 仍在執行中。請關閉所有 Lokum 視窗，然後點擊「重試」。"
LangString Preparing ${LANG_TRADCHINESE} "準備中…"
LangString Copying ${LANG_TRADCHINESE} "正在拆開你的 Lokum…"
LangString AppDescription ${LANG_TRADCHINESE} "Lokum — 更甜蜜的瀏覽方式"
LangString UnDataTitle ${LANG_TRADCHINESE} "你的瀏覽資料"
LangString UnDataSubtitle ${LANG_TRADCHINESE} "書籤、瀏覽紀錄、密碼與設定"
LangString UnDataText ${LANG_TRADCHINESE} "Lokum 會將書籤、瀏覽紀錄、密碼與設定儲存在使用者設定檔中。如果之後可能重新安裝 Lokum，請保留它們。"
LangString UnDataCheckbox ${LANG_TRADCHINESE} "同時刪除我的 Lokum 瀏覽資料"
